/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ComputadoresVista;

import Computadores.ComputadoresController;
import DaoComputadores.DaoComputadores;
import MenuPrincipal.MenuPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author HUMBERTO
 */
public class AgregarComputador extends javax.swing.JFrame {
    
    private static AgregarComputador instancia;

    /**
     * Creates new form AgregarComputador
     */
    public static AgregarComputador getInstancia()
   {
       if (instancia == null)
       {
           instancia = new AgregarComputador();
        
       }
       return instancia;
   }
   private AgregarComputador() {
        initComponents();
        
        setVisible (true);
        
     
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        GrupoComputadores = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFielCodigo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        Ch_Portatil = new javax.swing.JRadioButton();
        Ch_Escritorio = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFielMarca = new javax.swing.JTextField();
        Validacion1 = new javax.swing.JLabel();
        Validacion2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 490, 50));

        jPanel2.setBackground(new java.awt.Color(172, 199, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("codigo computador"));

        jTextFielCodigo.setText("Codigo");
        jTextFielCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFielCodigoMouseClicked(evt);
            }
        });
        jTextFielCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielCodigoActionPerformed(evt);
            }
        });
        jTextFielCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFielCodigoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTextFielCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFielCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 370, 70));

        jPanel5.setBackground(java.awt.SystemColor.activeCaption);
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GrupoComputadores.add(Ch_Portatil);
        Ch_Portatil.setText("Portatil");
        jPanel5.add(Ch_Portatil, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 18, 260, 27));

        GrupoComputadores.add(Ch_Escritorio);
        Ch_Escritorio.setText("Escritorio");
        Ch_Escritorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ch_EscritorioActionPerformed(evt);
            }
        });
        jPanel5.add(Ch_Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 18, 260, 27));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 530, 50));

        jButton1.setText("Guardar Computador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regresar.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 520, 110));

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Marca del computador"));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jTextFielMarca.setText("Marca");
        jTextFielMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFielMarcaMouseClicked(evt);
            }
        });
        jTextFielMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielMarcaActionPerformed(evt);
            }
        });
        jTextFielMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFielMarcaKeyTyped(evt);
            }
        });
        jPanel3.add(jTextFielMarca);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 370, 70));

        Validacion1.setText("*campo requerido");
        getContentPane().add(Validacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        Validacion2.setText("*campo requerido");
        getContentPane().add(Validacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         DaoComputadores compuCont = ComputadoresController .getInstance();
        String codigo = jTextFielCodigo.getText();
        String marca= jTextFielMarca.getText();
        String tipoComputador = "";
        if (Ch_Portatil.isSelected())
            tipoComputador += "portatil";
        
         if (Ch_Escritorio.isSelected())
            tipoComputador += "escritorio";
        
        String [] computador = {codigo,marca,tipoComputador};
        if (compuCont.GuardarComputador(computador))
            
            JOptionPane.showMessageDialog(this, "Guardado exitoso");
        
        // limpiar los campos de placa, nombre del usuario, y tipo de vehiculo
        
        jTextFielCodigo.setText("");
        jTextFielMarca.setText("");
        GrupoComputadores.clearSelection();
        
        
        MenuPrincipal menuOne = MenuPrincipal.getInstancia();
        menuOne.setVisible(true);
        this.dispose();
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menuOne = MenuPrincipal.getInstancia();
        menuOne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Ch_EscritorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ch_EscritorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ch_EscritorioActionPerformed

    private void jTextFielCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFielCodigoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielCodigoKeyTyped

    private void jTextFielCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFielCodigoMouseClicked
        // TODO add your handling code here:
        jTextFielCodigo.setText("");
    }//GEN-LAST:event_jTextFielCodigoMouseClicked

    private void jTextFielCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielCodigoActionPerformed

    private void jTextFielMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielMarcaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFielMarcaActionPerformed

    private void jTextFielMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFielMarcaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielMarcaKeyTyped

    private void jTextFielMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFielMarcaMouseClicked
        // TODO add your handling code here:
        jTextFielMarca.setText("");
    }//GEN-LAST:event_jTextFielMarcaMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Ch_Escritorio;
    private javax.swing.JRadioButton Ch_Portatil;
    private javax.swing.ButtonGroup GrupoComputadores;
    private javax.swing.JLabel Validacion1;
    private javax.swing.JLabel Validacion2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextFielCodigo;
    private javax.swing.JTextField jTextFielMarca;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
